printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
astroAllowShorthand: true
endOfLine: lf
plugins: ['prettier-plugin-astro']
overrides: [{ files: '**/*.astro', options: { parser: 'astro' } }]
